### ISSUE TITLE
Z3 check failed

### ISSUE THREAD

**Issue by Spottybadrabbit** [zenprotocol/zenwallet#102]
ZEN wallet will not load on npm

After running the npm installer I run `zen-wallet`

and I get this

https://ibb.co/ngwnm8

Running Ubuntu 16.04 Linux tegra-ubuntu 4.4.38-tegra #1 SMP PREEMPT Thu Jul 20 00:49:07 PDT 2017 aarch64 aarch64 aarch64 GNU/Linux

The Alpha worked perfectly.

**Comment by somdoron** [comment]
Which version of zen-wallet?
