### ISSUE TITLE
When I start zen-wallet it shows error "There was an uncaught error in the zen node"

### ISSUE THREAD

**Issue by un1t** [zenprotocol/zenwallet#113]
Ubuntu 16.04

zen-wallet 0.9.69

> Please copy and paste the following text and follow the steps at https://docs.zenprotocol.com/bug-bounty:
> 
> [15:38:48 INF] Node running... press CTRL+C to exit
> [15:38:49 ERR] Old version of mono, please upgrade
> 
> Unhandled Exception:
> System.NotImplementedException: The method or operation is not implemented.
> at Program.main (System.String[] argv) <0x406d4d50 + 0x00363> in <filename unknown>:0 
> [15:38:49 INF] Z3 check passed
> [ERROR] FATAL UNHANDLED EXCEPTION: System.NotImplementedException: The method or operation is not implemented.
> at Program.main (System.String[] argv) <0x406d4d50 + 0x00363> in <filename unknown>:0 

P.S. I did try to fill bug bounty form, but there is required field "Link to Loom video:" and I have not idea what is "Loom video" and I don't have any video to submit. I guess this field should be explained and probably not required.

**Comment by Cremba** [comment]
Did you install all the prerequisites? Check the Linux prerequisite on https://docs.zenprotocol.com/preparation/installers

**Comment by goldylucks** [comment]
@un1t Glad you resolved your issue and got the wallet running :)

I'm curious, was the text not clear enough?
> Old version of mono, please upgrade

Or maybe not highlighted enough?

what message do you think would have caught your attention and make you update mono to latest release?

**Comment by un1t** [comment]
It absolutely clear.  Not sure how I missed it.

**Comment by goldylucks** [comment]
yea happens to the best of us ;)
