### ISSUE TITLE
Unable to import seed, stuck on "importing..."

### ISSUE THREAD

**Issue by ripper234** [zenprotocol/zenwallet#117]
**Describe the bug**
I correctly entered my 24 words seed. At first, the `import` was grayed out. I clicked back, next, and refilled the 24 word seed. This time, `import` was clickable - so I clicked it.

Next thing I know the wallet is stuck on "importing..."

**Screenshots**

![image](https://user-images.githubusercontent.com/172282/44299230-ae9f4f80-a2fa-11e8-8639-45f0dd773973.png)

** Your machine and app Information **
- I'm on Windows
- Zen v0.9.69, official release

**Comment by Cremba** [comment]
Thank you for reporting this issue.
Take in to consideration that it usually take a some time to install a new wallet since is downloading all of the blockchain on your machine. 

Can you describe better what happened? 

Please contact me on telegram so that I can help you out more. @davidbrm

**Comment by ripper234** [comment]
In any case, this should not be the behavior.

I tried opening the wallet now again from scratch and it's just stuck on the Welcome to Zen Protocol screen forever, with the dots animation moving at the bottom ... but no estimate of when it's going to end.

![image](https://user-images.githubusercontent.com/172282/44305552-f669b980-a382-11e8-9db6-aca6212a906d.png)

I sent you a pm.

**Comment by ripper234** [comment]
Are there any debug logs I can activate / look for?
Where are the logs located anyway?

**Comment by Cremba** [comment]
You can open the developer window by pressing the right click of the mouse on the page and choose Inspect Element. 
Now in the bottom right, you will see the console tab. you should see something like this: 
<img width="586" alt="console log" src="https://user-images.githubusercontent.com/1292354/44306288-050c9c80-a394-11e8-9e8a-51e133487c60.png">

**Comment by ripper234** [comment]
This is how my log looks like, full of ERR_CONNECTION_REFUSED / Network
Errors




Ron Gross
+972-52-6558841
ripper234.com

**Comment by ripper234** [comment]
Oh, and actually the wallet opened now... but I don't see any funds or
transactions in it.








Ron Gross
+972-52-6558841
ripper234.com

**Comment by ripper234** [comment]
Oh, and actually the wallet opened now... but I don't see any funds or transactions in it.

![image](https://user-images.githubusercontent.com/172282/44312950-c06f1880-a408-11e8-89b7-bc18ad1b1e39.png)

![image](https://user-images.githubusercontent.com/172282/44312952-c2d17280-a408-11e8-862a-e34ecce93e6a.png)

**Comment by ripper234** [comment]
Ok, I went into Settings, clicked Wipe Blockchain (Wipe blockchain only), and now I see my funds.
(blockchain is syncing). Thanks!

It's up to you whether to keep this bug open or not - my problem is now resolved, but it should never have happened in the first place. The thing is I don't know exactly how to reproduce the problem...

Your call.

**Comment by Cremba** [comment]
Good, this problem happens on Windows 10, it has some issue connecting which result in a wrongfully added wallet, a simple Wipe Blockchain will solve the issue. 

If this issue happens again let's reopen this issue.  For now, the issue is solved
