### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by nunojesus** [zenprotocol/zenwallet#31]
Hi, How are you?
Im a graphic designer that like to help projects in opensource for free, so if you like I can contribute with graphic designs,, I can make you a logotype for this project if you want. So if you need some design just say it.

Greetings!
Nuno Jesus

**Comment by elanperach** [comment]
Hey Nuno,

Very cool, Your always welcome to try and submit a pull request. We do have an in-house designer that prepares our logos and designs.

Happy to see what you come up with

**Comment by nunojesus** [comment]
Do you have any request for the logo? Can you give me something to get inspired?C
Greetings!

**Comment by elanperach** [comment]
No special requests

https://www.zenprotocol.com/

**Comment by nunojesus** [comment]
The logo that you have in the website it´s the current logo?
