### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by xhipster** [zenprotocol/zenwallet#63]
This is screenshot

<img width="452" alt="screenshot 2018-07-01 19 33 43" src="https://user-images.githubusercontent.com/410789/42137053-f75665e8-7d65-11e8-948d-e062008114ce.png">

After accepting the error wallet continuously `Loading, please wait`

```
$ mono --version
Mono JIT compiler version 5.12.0.226 (tarball Tue Jun 26 14:05:36 BST 2018)
```
OSX: 10.13.5 (17F77)

Happens with the last 0.9.23 version of the wallet

**Comment by goldylucks** [comment]
@xhipster 
Thanks for reporting!
1. how did you install the wallet? (npm/dev/installer)
1. how are you running the wallet?
1. looks like it can't find your `mono` package, can you run `$ which mono` and copy the output?
1. did the wallet work on this machine before? and if so, which version?

**Comment by goldylucks** [comment]
@IsRod25 did you check the wallet on mac, version `0.9.23`?

**Comment by xhipster** [comment]
1. installer

**Comment by xhipster** [comment]
<img width="529" alt="screenshot 2018-07-02 11 57 55" src="https://user-images.githubusercontent.com/410789/42157895-33c3014c-7def-11e8-94a0-aa8a800d9e88.png">

The same with new version 0.9.25

**Comment by Cremba** [comment]
Please in order to install the latest version of mono don't use the brew installer but download it directly from http://www.mono-project.com/download/stable/#download-mac , this should solve your issue

**Comment by xhipster** [comment]
@Cremba thanks. The thing starts working?

> Please in order to install the latest version of mono don't use the brew installer

Why that could happens? It easier to maintain the stuff with help of brew on OSX
