### ISSUE TITLE
can open wallet on mac

### ISSUE THREAD

**Issue by jonimin** [zenprotocol/zenwallet#66]
Hi
I'm getting that error when i try to open the wallet
Tnx

![image](https://user-images.githubusercontent.com/26197231/42186465-7a4e65dc-7e55-11e8-8f02-09d8b170d1df.png)

**Comment by Cremba** [comment]
Please read https://docs.zenprotocol.com/preparation/installers

Right click on the ZPW (Zen-Protocol-Wallet)and choose 'open'
Confirm by clicking the 'open' button
