### ISSUE TITLE
Insufficient balance to send tokens

### ISSUE THREAD

**Issue by alegotardo** [zenprotocol/zenwallet#72]
Hello.

I have more than 1k of ZP in my wallet and I can't send more than 1 ZP to other wallet.
If I try to put 2 ZP, the wallet accuses that my balance is insufficient.

I think it's just a problem in representing of the number (points and commas).

All my wallet balance is already confirmed, because all the coins have been acquired in the pre-sale

![photo_2018-07-05_09-53-45](https://user-images.githubusercontent.com/40860228/42411412-0b395d70-81d2-11e8-88df-adc8ebd6224d.jpg)
![photo_2018-07-05_09-54-01](https://user-images.githubusercontent.com/40860228/42411413-0b5aed3c-81d2-11e8-8e3e-bee18f728286.jpg)
![photo_2018-07-05_09-54-17](https://user-images.githubusercontent.com/40860228/42411415-0b9ee7bc-81d2-11e8-887b-75b47db956b9.jpg)
![photo_2018-07-05_09-54-10](https://user-images.githubusercontent.com/40860228/42411414-0b7c7722-81d2-11e8-8ae8-202613eccda1.jpg)

**Comment by alegotardo** [comment]
I made several transfers of 1 ZP until I was less than 1k
And in this case I can try to send more coins than my balance... button is enabled and the wallet request my password.

![wallet_999](https://user-images.githubusercontent.com/40860228/42411363-ecac64fc-81d0-11e8-8a83-06591a5dc523.png)

However, the wallet doesn't allow me to complete the transaction.

![wallet_999_after_pw](https://user-images.githubusercontent.com/40860228/42411364-ecd2d6f0-81d0-11e8-93d7-79db06886631.png)

**Comment by alegotardo** [comment]
The images from first comment was edited to hide my address.

**Comment by alegotardo** [comment]
yes, this suspicion had already been reported to me on the telegram.
I even changed the settings and reopened my wallet but it didn't solve the problem.
![photo_2018-07-02_10-20-58](https://user-images.githubusercontent.com/40860228/42529889-0b5a265a-8456-11e8-9bed-02e7b2e28a14.jpg)

**Comment by ni-om** [comment]
I can confirm this exact problem. I think this is not about commas, but about the way GUI wallet represents 1k+ numbers: in, for example, 1300, they actually have a SPACE between 1 and 300, like 1 300, and that space makes wallet think I have only 1 zp, not 1300.

**Comment by somdoron** [comment]
Thanks, I think we know how to solve this and will release a fix today.

**Comment by alegotardo** [comment]
Unfortunately for me, the new version (0.9.42) has not solved the problem yet.

![13_07_2018](https://user-images.githubusercontent.com/40860228/42693124-75f42314-8684-11e8-9f1b-9bb251708cb2.jpg)

**Comment by alegotardo** [comment]
Wallet 0.2.44 fixed this bug, now I was able to do the transfer.
Thanks Doron and Elan for all attention provided in this problem.

**Comment by thecryptochef** [comment]
Just Watching the good work you guys are doing. 
My First post on Github.
